### ISSUE TITLE
GraphQLForeignKey doesn't work with "wagtailcore.Page" for content_type

### ISSUE THREAD

**Issue by zerolab** [GrappleGQL/wagtail-grapple#116]
trying to add `GraphQLForeignKey` pointing to `wagtailcore.Page` results in `Could not import 'grapple.schema.schema' for Graphene setting 'SCHEMA'. AttributeError: 'NoneType' object has no attribute '_meta'.`

Use case:
- an orderable with a page chooser that allows any type of page
- you want a list of chosen pages in the API

As far as I can see, the issue is around
https://github.com/GrappleGQL/wagtail-grapple/blob/e84622a8c67a0a684a59c1ba0d3448baf541a305/grapple/models.py#L81-L87 and the fact that the core page is not added to models. instead it is added as a `DjangoObjectType`

**Comment by tbrlpld** [comment]
I just ran into the same issue yesterday. What worked for me is [using the `GraphQLPage`](https://github.com/tbrlpld/headless-wagtail-form-backend/blob/4af521e8d09e9571c567fdb226d53b83445a55b9/forms/models.py#L61-L64) for the field that holds the backward relation of a foreign key relationship. 

The model creating the foreign key relationship (in my case a page) does know the class it is pointing to, while the pointed to model (in my case a form) does not know what kind of model is pointing to it, or more specifically it does not know which kind of page. In the schema, the field with the backward relation ship shows up to be of type `PageInterface`. 

Maybe this would work for your use case, but it is probably still a good idea to implement your suggested changes to make the behavior more consistent.

**Comment by zerolab** [comment]
Yeah, `GraphQLPage("field_name", source="method_that_returns_queryset", is_list=True)` did the trick.

I am tempted to close this as working as designed 🤔

**Comment by tbrlpld** [comment]
Awesome! Glad this "workaround" is working for your case too. 

If using the `GraphQLPage` field is the designed approach for this kind of relationship, we should maybe make that explicit in the [docs](https://wagtail-grapple.readthedocs.io/en/latest/general-usage/model-types.html) too (not sure how I found it in the first place 😅). Currently there is no mention of the `GraphQLPage` field model. I can also imagine that this is a common use case for foreign keys. It might make sense to explicitly reference that in the `GraphQLForeignKey` documentation also.

**Comment by zerolab** [comment]
@tbrlpld opened #119 with additions to docs. Would you be able to have a look/suggest improvements? Thanks

**Comment by tbrlpld** [comment]
@zerolab Of course, I will have a look!
