### ISSUE TITLE
Move away from accessing stream_data directly

### ISSUE THREAD

**Issue by zerolab** [GrappleGQL/wagtail-grapple#134]
Ref: https://github.com/wagtail/wagtail/pull/6485

tl;dr "external code should not be using stream_data"

**Comment by fabienheureux** [comment]
Won't this be fixed by https://github.com/GrappleGQL/wagtail-grapple/pull/172 ?

**Comment by zerolab** [comment]
Yep, that'll do it

**Comment by ruisaraiva19** [comment]
Fixed by #172 .
