### ISSUE TITLE
Support for Wagtail 2.12

### ISSUE THREAD

**Issue by ARogovskyy** [GrappleGQL/wagtail-grapple#156]
Is there any reason why Wagtail 2.12 isn't supported? A quick test with the included example doesn't seem to produce any errors. The changelog ( https://docs.wagtail.io/en/v2.12/releases/2.12.html ) isn't suggesting any big breaking changes either.

**Comment by zerolab** [comment]
Hey @ARogovskyy 
that would be the https://github.com/GrappleGQL/wagtail-grapple/blob/main/setup.cfg#L40 constraint.

Will look at adding a minor release with a version bump.

**Comment by ARogovskyy** [comment]
Yeah I'm aware, my question was more directed at if there's any code-related reason. Thanks for looking into it 👍

**Comment by zerolab** [comment]
hey @ARogovskyy i've now release 0.10.2 which should allow installation on 2.12.
Please let us know if you encounter any issues
