### ISSUE TITLE
Allow support for wagtail 2.13 and Django 3.2

### ISSUE THREAD

**Issue by sks444** [GrappleGQL/wagtail-grapple#173]
https://docs.wagtail.io/en/stable/releases/2.13.html

Allow the latest version of Django and Wagtail in the [install_requires](https://github.com/GrappleGQL/wagtail-grapple/blob/12f5977ae190fd291927fa38618f716920e5310f/setup.cfg#L40) of setup.cfg.

**Comment by sks444** [comment]
I see we already have a pr for this at https://github.com/GrappleGQL/wagtail-grapple/pull/172.

**Comment by fabienheureux** [comment]
I will restart working on this one next week @sks444, if ever you want to give a hand, feel free to help 👼
