### ISSUE TITLE
Add ability to use custom resolvers in the various GraphQLFields

### ISSUE THREAD

**Issue by ARogovskyy** [GrappleGQL/wagtail-grapple#179]
Oftentimes, one needs to preprocess some data before passing it to graphql, or just implement a fully cusomized property. For django models, this is possible by adding a `@property` and pointing a `GraphQLField` to it. However, for, say, custom `StructBlocks` (that were registered using `@register_streamfield_block`) there is currently no way to do that. More concretely, I would like to render the HTML output of Wagtail-markdown in a StructBlock to a GraphQL field.

One way to do that would be to add a possibility to pass a custom resolver to the GraphQLField, which is then taken instead of the default `streamfield_resolver` in actions.py, line 395. I could submit a PR if wanted.

**Comment by zerolab** [comment]
Hey @ARogovskyy, a PR would be more than welcome and much appreaciate!

I did find myself needing this a good while back, but there were a million things with higher priority and never got to it.

**Comment by zerolab** [comment]
WIP PR: #188

**Comment by zerolab** [comment]
#220 solves this

**Comment by zerolab** [comment]
callables and property support landed via #220
