### ISSUE TITLE
Add Image Focal point fields

### ISSUE THREAD

**Issue by sks444** [GrappleGQL/wagtail-grapple#193]
Documentation says we can access focal point fields for an [ImageObjectType](https://wagtail-grapple.readthedocs.io/en/latest/general-usage/graphql-types.html#imageobjecttype). But these fields are not available at the APIs.

Looks like we need to add them at [BaseImageObjectType](https://github.com/GrappleGQL/wagtail-grapple/blob/e92abab64ea0dcacf68cd68ccd64a66c055e55f6/grapple/types/images.py#L17)?

**Comment by zerolab** [comment]
@sks444 that is correct. Happy to submit a PR?
