### ISSUE TITLE
Prerequisites in README.md do not match setup.cfg

### ISSUE THREAD

**Issue by dopry** [GrappleGQL/wagtail-grapple#198]
We are evaluating using wagtail-grapple in a project, and there seems to be a mismatch in the prerequisites in the 

**README.md**
```markdown
Django  >= 2.2, <3.1 (<2.3 if using channels)
Wagtail >= 2.5, <2.13
```

and 

**setup.cfg**
```
install_requires =
    Django>=2.2
    wagtail>=2.11, <2.15
    graphene-django>=2.7.1, <2.14.0
    graphql-core>=2.2.1, <3
    wagtail-headless-preview

[options.extras_require]
channels =
    Django>=2.2
    channels>=3.0, <3.1
    channels_redis==3.3.0
    graphql-ws==0.4.4

```

The setup seems to indicate wagtail-grapple with channels will run fine on Django 3, While the README.md indicates we should be using <2.3.  I was hoping someone more knowledgeable than me could tell which is correct. It would be nice if the two references agreed.

**Comment by zerolab** [comment]
Hey @dopry 

The latest release does not fully support Django 3.2 (from #184), whereas the main branch does.
#197 will update the readme and with another PR, we should be good to make another release with full Wagtail 2.15 support too

**Comment by zerolab** [comment]
[v0.12.0](https://github.com/GrappleGQL/wagtail-grapple/releases/tag/v0.12.0) is now out
