### ISSUE TITLE
Version release with Wagtail 2.14 and 2.15 compatibility?

### ISSUE THREAD

**Issue by PeterDekkers** [GrappleGQL/wagtail-grapple#199]
Hello there. I'm wondering when your next release is planned to happen, to include compatibility with Wagtail 2.14 and 2.15. 

If anything is holding this release up that you could use assistance with, I'd be happy to pitch in.

Thanks!

**Comment by ruisaraiva19** [comment]
@PeterDekkers Thanks for reaching out!

There is one last [PR](https://github.com/GrappleGQL/wagtail-grapple/pull/182) that we wanna merge before the next release!

**Comment by zerolab** [comment]
Hey both,

#182 needs more considerations, so I went ahead and released [v0.12.0](https://pypi.org/project/wagtail-grapple/0.12.0/). Release notes at https://github.com/GrappleGQL/wagtail-grapple/releases/tag/v0.12.0

**Comment by PeterDekkers** [comment]
Amazing, thank you @zerolab and @ruisaraiva19.
