### ISSUE TITLE
Replace ugettext_lazy with gettext_lazy

### ISSUE THREAD

**Issue by 13hakta** [GrappleGQL/wagtail-grapple#201]
PyTest throws multiple warnings with:
`RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().`

**Comment by zerolab** [comment]
@13hakta thank for the report. Would gladly accept a PR that fixes this, and any other deprecation warnings
