### ISSUE TITLE
add django-filters in wagtail-grapple

### ISSUE THREAD

**Issue by warcivil** [GrappleGQL/wagtail-grapple#211]
hello, is it possible to add django-filters to wagtail grapple to filter graphql queries?

**Comment by zerolab** [comment]
Not at this point in time.

How would you see that working?

**Comment by warcivil** [comment]
is this supposed to happen in the future?
I didn't quite understand your question

**Comment by zerolab** [comment]
There are no plans to add django-filters to filter the graphql queries.

To make that happen we would need a solid plan, hence my asking how you imagine that working?

**Comment by warcivil** [comment]
I probably won't be able to answer your question
maybe answer my
1. is it possible to filter at least by the fields of the page object (url ...)
2. is it possible to filter through the wagtail engine (you also have indexed fields and filters there)
3. you can filter in python and not in the database

**Comment by zerolab** [comment]
you can filter by a number of things, see the graphiql interface for the schema.

e.g. for pages you can do id, slug, title, url_path, content_type, site

**Comment by airv-b** [comment]
Hello,

Maybe I have the same question.
Is it possible to exclude a result from a query? 

Example, I have the following query: 
```
{
  pages(contentType: "blog.blogPage", limit: 5) {
    title
    slug
    live
  }
}
```

and in response, I have: 

```
{
  "data": {
    "pages": [
      {
        "title": "test blog 1",
        "slug": "test-blog-1",
        "live": true
      },
      {
        "title": "test blog 2",
        "slug": "test-blog-2",
        "live": true
      },
      {
        "title": "test blog 3",
        "slug": "test-blog-3",
        "live": true
      },
      {
        "title": "test blog 4",
        "slug": "test-blog-4",
        "live": true
      },
      {
        "title": "test blog 5",
        "slug": "test-blog-5",
        "live": true
      }
    ]
  }
}

```
how can we have exclude (in the query) for example "slug: test-blog-5" and have this as a response : 

```
{
  "data": {
    "pages": [
      {
        "title": "test blog 1",
        "slug": "test-blog-1",
        "live": true
      },
      {
        "title": "test blog 2",
        "slug": "test-blog-2",
        "live": true
      },
      {
        "title": "test blog 3",
        "slug": "test-blog-3",
        "live": true
      },
      {
        "title": "test blog 4",
        "slug": "test-blog-4",
        "live": true
      },
      {
        "title": "test blog 6",
        "slug": "test-blog-6",
        "live": true
      }
    ]
  }
}
```

**Comment by zerolab** [comment]
At the moment that is not possible.
At the same time, we do have a mechanism for defining your own query - https://wagtail-grapple.readthedocs.io/en/latest/general-usage/hooks.html#query so I suggest using that

**Comment by zerolab** [comment]
Will go ahead and close this as I do not have the capacity or desire to add this for now
