### ISSUE TITLE
Add content type filter for the pages query

### ISSUE THREAD

**Issue by mansrz** [GrappleGQL/wagtail-grapple#31]
Hi, thanks for help me with last problem
Now,  i don't know if it is a bug or concept error mine, but if you can help me please can be help for other

I tried to get a page specific with filter by contenttype but i got null response, so i have to query "pages" instead "page" and can't filter by contenttype this cause me get many "{}" 
![DeepinScreenshot_select-area_20191103135934](https://user-images.githubusercontent.com/4426200/68090522-bd601c80-fe42-11e9-9bee-1769f03da607.png)
![DeepinScreenshot_select-area_20191103135955](https://user-images.githubusercontent.com/4426200/68090523-bd601c80-fe42-11e9-8ff1-f9043adbd658.png)

Example query: 
`{
  page(contentType:"home.AboutPage"){
    ... on AboutPage {
      contentType
      id
  }
}`

**Comment by SamuelTaylor001** [comment]
@mansrz why did you close this? Did you find a solution? I am getting the same issue with the following query

`query MyQuery {
  wagtail {
    pages {
      ... on NewsPage {
        id
        intro
        title
      }
    }
  }
}`

I realise that this could be fixed on the client side however, it defeats the purpose of GraphQL if we are forced to process unnecessary data.

Can we reopen this?

**Comment by mansrz** [comment]
I would believe that it should be opened, I closed it because I "solved it" at the moment doing the query by id but isn't the correct solution

**Comment by mcfarlanedev** [comment]
I'm also having a similar issue with multiple empty results being returned on a HomePage query. I only have one HomePage type in this example, and yet the results also includes empty objects:

`{
  pages {
    ... on HomePage {
      title
    }
  }
}
`
![image](https://user-images.githubusercontent.com/12474833/86512710-5002f200-bdfc-11ea-9add-4909c09a6c32.png)

**Comment by mcfarlanedev** [comment]
I'm also having a similar issue with multiple empty results being returned on a HomePage query. I only have one HomePage type in this example, and yet the results also includes empty objects:

`{ pages { ... on HomePage { title } } }
`

![](https://user-images.githubusercontent.com/12474833/86512710-5002f200-bdfc-11ea-9add-4909c09a6c32.png)

**Comment by NathHorrigan** [comment]
I can see how confusing this could be...

What do you think of the following choices @SamuelTaylor001:

```
page (contentType: "blogs.BlogPage") {
    ... on BlogPage {
         title
    }
}
```

will return the first result based on that contentType and will be the equivalent of the following ORM query: `BlogPage.objects.first()`

**Comment by isolationism** [comment]
I've added a PR for a solution that uses the `pageType` — I think `contentType` is something slightly different.

I am also filtering out the application prefix (i.e. the 'blog.' part of 'blog.BlogPage') to match the declared `pageType` returned in a query, but wonder if this isn't going to cause problems if two apps have the same model name.

**Comment by zerolab** [comment]
The reason the `{ page(contentType:"home.AboutPage"){ ... on AboutPage { contentType id } }` query fails is that the content type filter only kicks in if there is a preview token - https://github.com/GrappleGQL/wagtail-grapple/blob/master/grapple/types/pages.py#L197-L209

@isolationism thank you for #144 -- I think we should stick to content type as a filter to avoid namespace clashes.

Will open a new PR to fix the filter on content type (an credit you on it as well, @isolationism )

**Comment by zerolab** [comment]
https://github.com/GrappleGQL/wagtail-grapple/pull/147

all reviews are welcome
