### ISSUE TITLE
example app docker build fails 

### ISSUE THREAD

**Issue by easherma** [GrappleGQL/wagtail-grapple#39]
![example](https://user-images.githubusercontent.com/10539855/70173238-11575e80-1698-11ea-86c7-c8feb189c283.png)

**Comment by tbrlpld** [comment]
A bit more details would be helpful. Did you make the `requirements.txt` available in the Docker container (either by copying it or by mounting the directory it lives in as a volume)?

**Comment by tbrlpld** [comment]
@easherma Just looking at the output again, the error message looks curious. `No such file or directory: '/code/../requirements.txt'`.

Where is the `/../` coming from? This would mean that the `requirements.txt` is expected in the root directory `/`.

**Comment by zerolab** [comment]
ah.. example/requirements.txt references the root requirements.txt (as ../requirements.txt) which explains this. I would copy the root requirements.txt in your container

**Comment by zerolab** [comment]
This is fixed by #210
