### ISSUE TITLE
Runtime warnings

### ISSUE THREAD

**Issue by stan-sack** [GrappleGQL/wagtail-grapple#46]
Hey, I'm getting a couple of warnings when I run my project:

The first one is as follows:
```
/<my-venv>/lib/python3.7/site-packages/django/db/models/base.py:316: RuntimeWarning: Model 'grapple.stubmodel' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
```
This only happens when I pass my blog app in `GRAPPLE_APPS`.

The second one is:
```
/<my-venv>/lib/python3.7/site-packages/wagtail/documents/models.py:27: RemovedInWagtail210Warning: wagtail.documents.models.get_document_model has been moved to wagtail.documents.get_document_model
```
I guess we should maybe update to the new `get_document_model` implementation. I can try and make a PR if I have time.

**Comment by timmysmalls** [comment]
I also have the first one. I also notice that whenever I make migrations globally, so `manage.py makemigrations` without specifying an app, it adds a new migration for grapple. Something about removing the stubmodel.

**Comment by zerolab** [comment]
@stan-sack @timmysmalls can you check #133 ?
