### ISSUE TITLE
Confusing docstring in PageInterface

### ISSUE THREAD

**Issue by leewesleyv** [GrappleGQL/wagtail-grapple#69]
The docstring of `resolve_children()` reads: "Resolves a list of live children of this page with `show_in_menus` set." (I guess [this](https://docs.wagtail.io/en/stable/reference/pages/queryset_reference.html#examples) is the source of the docstring). The function however, does not filter live child pages, nor does it filter on `show_in_menus`.

I wouldn't mind making a PR to resolve this issue, but I don't know if this function should be returning live pages only (filtering for `show_in_menus` does not make sense here IMO).

Is the docstring or the query invalid?

**Useful links:**
- https://github.com/torchbox/wagtail-grapple/blob/master/grapple/types/pages.py#L65-L70

**Comment by zerolab** [comment]
Thank you for this. Fixed in c0932f2. The docstring was erroneous
