### ISSUE TITLE
Unable to map ClusterTaggableManager 

### ISSUE THREAD

**Issue by SamuelTaylor001** [GrappleGQL/wagtail-grapple#70]
Hi,

I'm using the tag manager for wagtail to tag some of my posts however, I've noticed that grapple doesn't know how to interpret ClusterTaggableManager.

This is how my class looks
``` python
class FactSheetTag(TaggedItemBase):
    content_object = ParentalKey(
        'FactSheet',
        related_name='tagged_items',
        on_delete=models.CASCADE
    )
```

This is how my field looks
``` python
keywords = ClusterTaggableManager(through=FactSheetTag, blank=True)
```

This is the output from graphene's converter.py file:
```
Exception: Don't know how to convert the Django field fact_sheet.FactSheet.keywords (<class 'modelcluster.contrib.taggit.ClusterTaggableManager'>)
```

When previously trying to implement my own Graphene coverter for Wagtail, I used the following code.

``` python
class FlatTags(graphene.String):
    @classmethod
    def serialize(cls, value):
        tagsList = []
        for tag in value.all():
            tagsList.append(tag.name)
        return tagsList

@convert_django_field.register(ClusterTaggableManager)
def convert_tag_field_to_string(field, registry=None):
    return graphene.Field(FlatTags,
        description=field.help_text,
        required=not field.null)
```

Does a similar implementation already exist in wagtail-grapple that I have missed or should this be a feature request?

Also, how might I implement this feature in the case that ClusterTaggableManager is not supported at all?

**Comment by IAmNatch** [comment]
@SamuelTaylor001 I have mapped ClustTaggableManager to a graphQL field in the past. I think I based most of the implementation of this article: https://jossingram.wordpress.com/2018/04/19/wagtail-and-graphql/

If it would be beneficial for you, I'd be happy to find out exactly how I implemented it and post here. 

Note that implementing this will require you to have your own custom graphQL schema that you merge with grapples. It should be perfectly feasible, as outlined in https://github.com/torchbox/wagtail-grapple/issues/33

Let me know if this was useful!

**Comment by tbrlpld** [comment]
@IAmNatch Thanks for that. That works, but only gets me a string representation of the tags. I wish I could extracted the data in a more structured format.

**Comment by tbrlpld** [comment]
Ok, I am massively confused. For some reason, once there is any method registered with `@convert_django_field.register(ClusterTaggableManager)` for `ClusterTaggableManager` it will show the tags as a list. 

```graphql
query Pages {
  pages {
    ... on BlogPage {
      id
      title
      tags 
    }
  }
}
```
-> 
```json
{
  "data": {
    "pages": [
      {},
      {},
      {},
      {
        "id": "5",
        "title": "First article",
        "tags": "[<Tag: first>]"
      },
      {
        "id": "6",
        "title": "Another Article",
        "tags": "[<Tag: other>, <Tag: space>]"
      },
      {}
    ]
  }
}
```

This works even when the registered function is completely nonsensical (like just returns `None`). 
```python
@convert_django_field.register(ClusterTaggableManager)
def convert_tag_manager_to_string(field, registry=None):
    return None
```

What is going on here? I ran into this, because I was trying to customize the return string to start understanding some more about how this could be achieved. 

```python

class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        'BlogPage',
        related_name='tagged_items',
        on_delete=models.CASCADE,
    )

class BlogPage(Page):
    ...
    tags = ClusterTaggableManager(
        through=BlogPageTag,
        blank=True,
    )

    ...

    graphql_fields = [
        ...
        GraphQLString("tags"),
        ...
    ]
```

Is this the behavior you get too?

**Comment by tbrlpld** [comment]
Ok, I was able to figure something out. To enable Grapple to make use of a custom type, the generic `GraphQLField` needs to be used with the custom type. 

Here is how I put it to use:
```python
# blog/schema.py

import graphene
from graphene_django.converter import convert_django_field
import grapple.models as gpl
import modelcluster.contrib.taggit as mct
import taggit.models as tgt


@convert_django_field.register(mct.ClusterTaggableManager)
def convert_tag_manager_to_string(field, registry=None):
    """Define converter type for ClusterTaggableManager."""
    return TagType()


class TagType(graphene.ObjectType):
    """Tag GraphQL Type."""

    tag_id = graphene.Int(name='id')
    name = graphene.String()

    def resolve_tag_id(self, _):  # noqa: D102
        return self.id

    def resolve_name(self, _):  # noqa: D102
        return self.name


class TagQuery(graphene.ObjectType):
    """Queries for the TagType."""

    tag = graphene.Field(TagType, id=graphene.Int())
    tags = graphene.List(TagType)

    def resolve_tag(self, _, id):  # noqa: D102
        return tgt.Tag.objects.get(pk=id)

    def resolve_tags(self, _):  # noqa: D102
        return tgt.Tag.objects.all().order_by('pk')


def GraphQLTags(field_name: str, **kwargs):  # noqa: N802
    """Custom grapple wrapper function for the TagType."""
    def Mixin():
        return gpl.GraphQLField(field_name, TagType, is_list=True, **kwargs)

    return Mixin
```

```python
# blog/models.py

from blog.schema import GraphQLTags
...

class BlogPage(Page):
    ...
    tags = ClusterTaggableManager(
        through=BlogPageTag,
        blank=True,
    )

   ...
    graphql_fields = [
        ...
        GraphQLTags("tags"),
        ...
    ]
