### ISSUE TITLE
Django 3 Compatiblity

### ISSUE THREAD

**Issue by IAmNatch** [GrappleGQL/wagtail-grapple#73]
Hey there! I'm wondering if there's plans to make this compatible with Django 3 and ASGI?

**Comment by timmysmalls** [comment]
@NathHorrigan I'd like to resolve this. I'd like to be able to use Grapple with Wagtail 2.9 and Django 3.0. I'm not sure if you're aware of any things that need to change in order for things to work? Or is it just a matter of "update the dependencies and see what breaks"?

**Comment by NathHorrigan** [comment]
I haven’t had the chance to test it yet, I’m open to accepting any error logs, bugs etc

**Comment by zerolab** [comment]
In order to support Django 3.0, we need to upgrade the channels side of things.
I propose we make channels support optional (as per #86)

**Comment by zerolab** [comment]
@IAmNatch @timmysmalls made a start on this last night - #89 could use some help with testing
